module.exports = `
query UserInfo($email:String!,$domain:String!){
  me:user_information(where:{
    email:{_eq:$email},
    domain:{_eq:$domain}
  }){
    user_id
    user_info{
      displayName
      email
      first_name
      last_name
      image_url
      gender      
    }
    roles:role_names
  	organization_information:organization{
      id
      organization_name    
      modules{
        id
        module{
          module_name
          url
        }
      }
    }    
  }
}`
