query OrganizationListQuery {
  organizations{
    domain
    id
  }
}

subscription OrganizationListSubscription {
  organizations{
    domain
    id
  }
}

query GetOrgInfo($domain:String!){
  organizations(where:{domain:{_eq:$domain}}){
    id
    domain
    api_domain
    organization_name
    modules{
      module{
        id
        module_name
      }      
    }
  }
}
