subscription SubscribeKhoas {
  khoas{
    id
    ten_khoa
    giang_vien_id
  }
}

query GetKhoas {
  khoas{
    id
    ten_khoa
    giang_vien_id
  }
}

query QuerySubjects {
  v_get_all_subject_class{
    tuan
    ma_lop
    ma_mon_hoc
    ten_mon_hoc
  }
}

subscription SubscribeSubjects {
  v_get_all_subject_class{
    tuan
    ma_lop
    ma_mon_hoc
    ten_mon_hoc
  }
}